<a href="https://colab.research.google.com/github/Mrfrktmrck19/Data_Science/blob/master/TensorFlow/3.CreateModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

After we splitted datas, we should create a model. But before we have to follow a few steps.
1. Scaling data. we will change the size of ONE data. Because we want operations be faster.

In [1]:
import numpy as np
import pandas as pd
import tensorflow as ts
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/bisiklet_fiyatlari.xlsx")

In [3]:
df.head()

Fiyat  BisikletOzellik1  BisikletOzellik2
0  807.673876       1749.628226       1749.590668
1  959.227520       1748.007826       1751.824206
2  718.020033       1750.122967       1747.977026
3  945.668885       1749.916440       1750.771646
4  955.542968       1750.780519       1750.592430

In [8]:
# Spit datas to x(features) and y(label)
y = df["Fiyat"].values
x = df[["BisikletOzellik1","BisikletOzellik2"]].values

In [14]:
y.shape # 1000,
x.shape # 1000,2

(1000, 2)

In [ ]:
# for i,j in x:
#   print(i," ",j)

In [16]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.33, #test size 0.33 train size #0.67
    random_state=15
)

In [17]:
print(type(x_train),type(x_test),type(y_train),type(y_test))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [20]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(670, 2) (330, 2) (670,) (330,)


In [24]:
print(x_train[0:5],"\n\n\n",x_test[:5],"\n\n\n",y_train[0:5],"\n\n\n",y_test[:5])

[[1748.374239 1751.217187]
 [1751.580415 1753.658535]
 [1750.727042 1745.942278]
 [1747.083344 1751.701046]
 [1748.382781 1750.342128]] 


 [[1751.019597 1751.83637 ]
 [1749.850949 1747.23938 ]
 [1750.837436 1749.641408]
 [1748.122661 1751.075311]
 [1747.681905 1751.334307]] 


 [ 928.6952754 1263.961903   539.3910047  909.0602356  827.5599926] 


 [1081.652164   622.6759897  889.3568099  902.8267326  897.6624037]


## Scaling Data

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
scaler = MinMaxScaler() # generate an object

In [28]:
scaler.fit(x_train) #firstly,we need to make the data fit.

MinMaxScaler()

In [29]:
x_train = scaler.transform(x_train) #then, resizing to [0:1]
x_test = scaler.transform(x_test)

The reason we do this is to process data easier and faster.

In [36]:
x_train[0:5],"============================",x_test[0:5]

(array([[0.3177906 , 0.64341466],
        [0.61991638, 0.89583174],
        [0.53950097, 0.0980286 ],
        [0.19614642, 0.69344205],
        [0.31859554, 0.55294012]]),
 '============================',
 array([[0.56706914, 0.70743354],
        [0.45694459, 0.23213923],
        [0.54990366, 0.48049092],
        [0.2940838 , 0.62874574],
        [0.25255028, 0.65552399]]))

Now, we can feed above datas to our model. For this, we will use tensorflow and keras.
Sequential is class that our model. We generate our model from this class.We determine with which layers our model will work.

In [38]:
from tensorflow.keras.models import Sequential #generate a model
from tensorflow.keras.layers import Dense   #generate a layers

In [39]:
model = Sequential() # we generated a model. :)The hard part is creating the layers.

model.add(Dense(5,activation="relu"))  #5 neuron
model.add(Dense(5,activation="relu"))  #5 neuron
model.add(Dense(5,activation="relu"))  #5 neuron
# and three hidden layers
model.add(Dense(1))  #output layer

# We are combining our work so far.
model.compile(optimizer ="rmsprop",loss="mse")
