<a href="https://colab.research.google.com/github/Mrfrktmrck19/Data_Science/blob/master/Manipulation/1_Nump101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# Numpy

## Intro

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

a*b

array([ 6, 14, 24, 36, 50])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
type(b)

numpy.ndarray

In [ ]:
np.zeros(10, dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full((3,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [ ]:
type(np.full((3,5),5))

numpy.ndarray

In [ ]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
type(np.arange(0,30,3))

numpy.ndarray

In [ ]:
np.linspace(0.5,10,20)

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.random.normal(10,4,(3,4)) # mean = 10, standart deviation = 4, size = (3,4)

array([[14.46149636, 14.5187976 ,  1.71987622,  4.48918078],
       [ 9.84334825, 13.13408529, 11.5241058 , 12.59997227],
       [11.27626061,  8.04193481, 16.15784417,  6.34623911]])

In [ ]:
np.random.randint(0,10, (3,3))

array([[8, 1, 1],
       [7, 8, 8],
       [7, 3, 1]])

## Features of Numpy Array

In [ ]:
a = np.random.randint(low = 2, high = 20, size = 20)
a

array([ 5, 16, 18,  7,  5, 13, 13,  2, 19, 12, 16, 19, 16, 13, 14, 15,  2,
       15,  5,  3])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(20,)

In [ ]:
a.size

20

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b = np.random.randint(low = 2, high = 15, size = (5,4))
b

array([[ 6, 13, 12, 12],
       [ 8,  2, 13, 10],
       [ 7,  3,  9,  2],
       [ 3,  9, 12, 10],
       [12,  7,  7,  4]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(5, 4)

In [ ]:
b.size   # 5*4 = 20

20

In [ ]:
b.dtype

dtype('int64')

## reshape() Function

Somestimes you need to convert your array to a matris or 2d array. Because some libraries (especially neural network libraries) accept matris or 2d/3d array.

In [ ]:
a = np.arange(2,45,3)
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [ ]:
len(a)

15

In [ ]:
a.size

15

we can convert to 3X5 or 5X3 type.

In [ ]:
help(a.reshape((3,5)))

In [ ]:
a.reshape((3,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29],
       [32, 35, 38, 41, 44]])

In [ ]:
a # need to save

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [ ]:
a = a.reshape((3,5))
a

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29],
       [32, 35, 38, 41, 44]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 5)

In [ ]:
a = a.reshape((5,3))
a

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26],
       [29, 32, 35],
       [38, 41, 44]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(5, 3)

## Concatenation

In [ ]:
x = np.arange(0,31,3)
y = np.arange(33,61,3)

In [ ]:
z = np.concatenate([x,y])

In [ ]:
z

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60])

In [ ]:
a = np.random.randint(1,15,size=(4,5))

In [ ]:
a

array([[14,  5,  5, 11,  4],
       [14,  3,  5,  8, 10],
       [13, 13,  9,  9, 12],
       [13,  1,  1,  8,  2]])

In [ ]:
b = np.random.randint(16,30,size=(4,5))
b

array([[21, 26, 20, 27, 24],
       [28, 18, 19, 18, 20],
       [22, 24, 23, 28, 24],
       [28, 17, 22, 20, 25]])

In [ ]:
c = np.concatenate([a,b]) # row based

In [ ]:
c

array([[14,  5,  5, 11,  4],
       [14,  3,  5,  8, 10],
       [13, 13,  9,  9, 12],
       [13,  1,  1,  8,  2],
       [21, 26, 20, 27, 24],
       [28, 18, 19, 18, 20],
       [22, 24, 23, 28, 24],
       [28, 17, 22, 20, 25]])

In [ ]:
d = np.concatenate([a,b], axis = 1)  # column based
d

array([[14,  5,  5, 11,  4, 21, 26, 20, 27, 24],
       [14,  3,  5,  8, 10, 28, 18, 19, 18, 20],
       [13, 13,  9,  9, 12, 22, 24, 23, 28, 24],
       [13,  1,  1,  8,  2, 28, 17, 22, 20, 25]])

## Array Splitting

In [ ]:
a = np.random.randint(1,20,size=20)
a

array([18,  7, 11, 15,  1, 10,  7, 16, 17,  7, 16,  9, 13, 11, 13,  3, 15,
        3,  7, 16])

In [ ]:
np.split(a,[3,5]) # firstly separte 2nd index, then separete 4th index, lastly separate rest of list

[array([18,  7, 11]),
 array([15,  1]),
 array([10,  7, 16, 17,  7, 16,  9, 13, 11, 13,  3, 15,  3,  7, 16])]

In [ ]:
np.split(a, [3,6,10])

[array([18,  7, 11]),
 array([15,  1, 10]),
 array([ 7, 16, 17,  7]),
 array([16,  9, 13, 11, 13,  3, 15,  3,  7, 16])]

In [ ]:
x,y,z = np.split(a,[3,7])

In [ ]:
print(x)
print(y)
print(z)

[18  7 11]
[15  1 10  7]
[16 17  7 16  9 13 11 13  3 15  3  7 16]


In [ ]:
m = np.arange(16).reshape((4,4))

In [ ]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# np.vsplit() for 2d array, row based

In [ ]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
a,b = np.vsplit(m,[2])
print(a)
print("==================")
print(b)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# np.hsplit() for 2nd array, column based

In [ ]:
a,b = np.hsplit(m,[2]) 
print(a)
print("==================")
print(b)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


you can use vsplit and hsplit function to separete 2d array. However, split function has "axis" argument. this might help you.

In [ ]:
m = np.arange(16).reshape((4,4))

In [ ]:
a,b=np.split(m,[2])  # axis default 0, row based
print(a)
print("========")
print(b)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
a,b=np.split(m,[2],axis = 1) # axis accept 1, column based
print(a)
print("=========")
print(b)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Sorting

In [ ]:
a = np.random.randint(0, 50, size = 20)

In [ ]:
a

array([33, 31, 17, 47, 18, 41, 27,  1, 18, 38, 16, 44, 33,  4, 49, 25,  3,
       16, 29, 49])

In [ ]:
np.sort(a)

array([ 1,  3,  4, 16, 16, 17, 18, 18, 25, 27, 29, 31, 33, 33, 38, 41, 44,
       47, 49, 49])

In [ ]:
a.sort()

In [ ]:
a

array([ 1,  3,  4, 16, 16, 17, 18, 18, 25, 27, 29, 31, 33, 33, 38, 41, 44,
       47, 49, 49])

In [ ]:
arr2d = np.random.normal(20,5,(3,3))
arr2d

array([[12.01531698, 22.55070296, 21.40011016],
       [13.8004838 , 17.90964556, 26.7314666 ],
       [14.66029605, 15.72856188, 19.96258164]])

In [ ]:
np.sort(arr2d) # sorting inside the rows, not all matris

array([[12.01531698, 21.40011016, 22.55070296],
       [13.8004838 , 17.90964556, 26.7314666 ],
       [14.66029605, 15.72856188, 19.96258164]])

In [ ]:
np.sort(arr2d, axis =1) 

array([[12.01531698, 21.40011016, 22.55070296],
       [13.8004838 , 17.90964556, 26.7314666 ],
       [14.66029605, 15.72856188, 19.96258164]])

In [ ]:
arr2d.shape

(3, 3)

## Selecting Elements

In [ ]:
 m = np.random.randint(0,45,size=(5,5))

In [ ]:
m[1,2]

36

In [ ]:
m[1:2,2:4]

array([[36, 27]])

In [ ]:
m[1:4,1:4]

array([[35, 36, 27],
       [ 6, 12, 29],
       [29, 34, 26]])

In [ ]:
m

array([[12, 23, 27, 11, 36],
       [39, 35, 36, 27, 33],
       [24,  6, 12, 29, 16],
       [26, 29, 34, 26, 21],
       [ 8, 12, 28, 17, 41]])

In [ ]:
m[-1]

array([ 8, 12, 28, 17, 41])

In [ ]:
m[-1,-1]

41

In [ ]:
m[2,2] = 20
m

array([[12, 23, 27, 11, 36],
       [39, 35, 36, 27, 33],
       [24,  6, 20, 29, 16],
       [26, 29, 34, 26, 21],
       [ 8, 12, 28, 17, 41]])

## Subset, Slicing

In [ ]:
a = np.arange(0,45,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44])

In [ ]:
a[1:6]

array([ 2,  4,  6,  8, 10])

In [ ]:
a[1:6:2]

array([ 2,  6, 10])

In [ ]:
a[::2]

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44])

In [ ]:
a[2::4]

array([ 4, 12, 20, 28, 36, 44])

In [ ]:
## 2d array 

In [ ]:
m = np.random.randint(0,45,size=(5,5))

In [ ]:
m

array([[ 9, 19, 31, 17, 26],
       [23, 35, 27, 17,  6],
       [17, 36, 22, 28, 27],
       [ 7, 36,  2, 14,  5],
       [34,  0, 32, 21, 36]])

In [ ]:
m[1:3,1:3]

array([[35, 27],
       [36, 22]])

In [ ]:
m[:,:]

array([[ 9, 19, 31, 17, 26],
       [23, 35, 27, 17,  6],
       [17, 36, 22, 28, 27],
       [ 7, 36,  2, 14,  5],
       [34,  0, 32, 21, 36]])

In [ ]:
m[:,1]

array([19, 35, 36, 36,  0])

In [ ]:
m[1,:]

array([23, 35, 27, 17,  6])

In [ ]:
subset_a = m[:,2:5]
subset_a

array([[31, 17, 26],
       [27, 17,  6],
       [22, 28, 27],
       [ 2, 14,  5],
       [32, 21, 36]])

In [ ]:
subset_a[2,2] = 99999
subset_a

array([[   31,    17,    26],
       [   27,    17,     6],
       [   22,    28, 99999],
       [    2,    14,     5],
       [   32,    21,    36]])

In [ ]:
m

array([[    9,    19,    31,    17,    26],
       [   23,    35,    27,    17,     6],
       [   17,    36,    22,    28, 99999],
       [    7,    36,     2,    14,     5],
       [   34,     0,    32,    21,    36]])

In [ ]:
subset_b= m[:,2:5].copy()

In [ ]:
subset_b

array([[   31,    17,    26],
       [   27,    17,     6],
       [   22,    28, 99999],
       [    2,    14,     5],
       [   32,    21,    36]])

In [ ]:
subset_b[2,2] = 111111111111
subset_b

array([[          31,           17,           26],
       [          27,           17,            6],
       [          22,           28, 111111111111],
       [           2,           14,            5],
       [          32,           21,           36]])

In [ ]:
m # as you can see, subset_b is independet value

array([[    9,    19,    31,    17,    26],
       [   23,    35,    27,    17,     6],
       [   17,    36,    22,    28, 99999],
       [    7,    36,     2,    14,     5],
       [   34,     0,    32,    21,    36]])

## Fancy Index

similar logic in r, which() func.

In [ ]:
m = np.arange(0,31,3)
m

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
m[1],m[2],m[5]

(3, 6, 15)

In [ ]:
retrieveDatabyIndex = [1,5,8]
m[retrieveDatabyIndex]

array([ 3, 15, 24])

It get element by INDEX

In [ ]:
 # 2d array

In [ ]:
m = np.arange(0,25).reshape((5,5))
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
getXaxis = [0,1,2]
getYaxis = [3,3,3]
m[getXaxis,getYaxis]    # totally, it returns 3 elements. these values (getXaxis, getYaxis) are coordinate numbers. m[0,3],m[1,3],m[2,3]

array([ 3,  8, 13])

In [ ]:
getXaxis = [0,1,2]
getYaxis = [1,2,3]
m[getXaxis,getYaxis]

array([ 1,  7, 13])

In [ ]:
m[0,1:3] # returns 1,2

array([1, 2])

In [ ]:
m[0,[1,2]] # returns same, but dont forget, they are index. Just like in R.

array([1, 2])

In [ ]:
m[:,[2,3,4]]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

## Conitions

In [ ]:
x = np.arange(0,31,3)
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
x<5 # it returns True,False values

array([ True,  True, False, False, False, False, False, False, False,
       False, False])

In [ ]:
x[x<5] # it returns values.

array([0, 3])

In [ ]:
x[x > 5] 

array([ 6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
x[x >= 5] 

array([ 6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
x[x <= 5] 

array([0, 3])

In [ ]:
x[x==5] 

array([], dtype=int64)

In [ ]:
x[x == 6] 

array([6])

In [ ]:
x[x != 6] 

array([ 0,  3,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
# fantasy

#x[x <27 and x>3]
# x[x[x>3]<27] # index error
# a=x[x>3]

# a 

# Pandas

## Pandas Series

## intro


Indexes of Values is contained with values.

In [ ]:
pd.Series([54,65,89,54,12,36,53,23])

0    54
1    65
2    89
3    54
4    12
5    36
6    53
7    23
dtype: int64

In [ ]:
type(pd.Series([54,65,89,54,12,36,53,23]))

pandas.core.series.Series

In [ ]:
seri = pd.Series([54,65,89,54,12,36,53,23])
seri.axes

[RangeIndex(start=0, stop=8, step=1)]

In [ ]:
seri.dtype

dtype('int64')

In [ ]:
seri.shape

(8,)

In [ ]:
seri.ndim

1

In [ ]:
seri.head()

0    54
1    65
2    89
3    54
4    12
dtype: int64

In [ ]:
seri.head(2)

0    54
1    65
dtype: int64

In [ ]:
seri.tail(2)

6    53
7    23
dtype: int64

In [ ]:
seri = pd.Series([23,24,21,22,20,21,23], index= ["Candidate_1","Candidate_2","Candidate_3","Candidate_4","Candidate_5","Candidate_6","Candidate_7"])
seri

Candidate_1    23
Candidate_2    24
Candidate_3    21
Candidate_4    22
Candidate_5    20
Candidate_6    21
Candidate_7    23
dtype: int64

In [ ]:
seri["Candidate_1":"Candidate_5"]

Candidate_1    23
Candidate_2    24
Candidate_3    21
Candidate_4    22
Candidate_5    20
dtype: int64

In [ ]:
sozluk = pd.Series({"reg":10,"log":12,"cart":12})

In [ ]:
sozluk

reg     10
log     12
cart    12
dtype: int64

In [ ]:
 x = {"a":10, "b":10,"a":20}

In [ ]:
x

{'a': 20, 'b': 10}

In [ ]:
x["a"]

20

In [ ]:
seriA = pd.Series([12,23,34,45,56,67,78,89,99])
seriB = pd.Series([31,64,97,82,94,76,28,17,39])
seri=pd.concat([seriA,seriB])

In [ ]:
seri

0    12
1    23
2    34
3    45
4    56
5    67
6    78
7    89
8    99
0    31
1    64
2    97
3    82
4    94
5    76
6    28
7    17
8    39
dtype: int64

## Eleman operators

In [ ]:
x = np.random.normal(20,5,size=20)
x

array([25.1758222 , 25.26704577, 24.45911719, 21.32587273, 13.84553358,
       20.10170526, 18.8872657 , 26.85559708, 21.89872453, 26.06489775,
       26.3189577 , 19.46810295, 12.89680234, 13.35209372, 28.10044212,
       20.45432179, 20.64215882, 25.96553113, 23.60850573, 15.17555167])

In [ ]:
seri = pd.Series(data=x)
seri

0     25.175822
1     25.267046
2     24.459117
3     21.325873
4     13.845534
5     20.101705
6     18.887266
7     26.855597
8     21.898725
9     26.064898
10    26.318958
11    19.468103
12    12.896802
13    13.352094
14    28.100442
15    20.454322
16    20.642159
17    25.965531
18    23.608506
19    15.175552
dtype: float64

In [ ]:
seri[0:3]

0    25.175822
1    25.267046
2    24.459117
dtype: float64

In [ ]:
seri.index

RangeIndex(start=0, stop=20, step=1)

In [ ]:
seri.keys

<bound method Series.keys of 0     25.175822
1     25.267046
2     24.459117
3     21.325873
4     13.845534
5     20.101705
6     18.887266
7     26.855597
8     21.898725
9     26.064898
10    26.318958
11    19.468103
12    12.896802
13    13.352094
14    28.100442
15    20.454322
16    20.642159
17    25.965531
18    23.608506
19    15.175552
dtype: float64>

In [ ]:
list(seri.items())

[(0, 25.17582220334937),
 (1, 25.267045774077395),
 (2, 24.459117188053437),
 (3, 21.325872732601994),
 (4, 13.845533582759279),
 (5, 20.101705256325815),
 (6, 18.887265701899068),
 (7, 26.855597083280983),
 (8, 21.898724529589458),
 (9, 26.064897748925553),
 (10, 26.318957699226715),
 (11, 19.46810294625962),
 (12, 12.89680233898541),
 (13, 13.352093722426666),
 (14, 28.100442124289092),
 (15, 20.454321785847622),
 (16, 20.642158815461706),
 (17, 25.965531126674577),
 (18, 23.60850572699176),
 (19, 15.175551673924268)]

In [ ]:
seri.values

array([25.1758222 , 25.26704577, 24.45911719, 21.32587273, 13.84553358,
       20.10170526, 18.8872657 , 26.85559708, 21.89872453, 26.06489775,
       26.3189577 , 19.46810295, 12.89680234, 13.35209372, 28.10044212,
       20.45432179, 20.64215882, 25.96553113, 23.60850573, 15.17555167])

In [ ]:
25.17582220334937 in seri

False

In [ ]:
2 in seri # index

True

## Pandas DataFrame

In [ ]:
pd.DataFrame(data = [1,2,3,4,5,6,7,8,9,10], columns= ["Number"])

Number
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10

In [ ]:
x = np.random.normal(25,6,size=20)
x

array([28.87307069, 22.04842749, 22.0252848 , 26.53469703, 23.73990426,
       32.09556467, 26.70994342, 23.10093244,  8.25476803, 32.77321634,
       22.61460025, 38.69310383, 16.08313959,  3.89219062, 21.89102814,
       22.91346405, 21.67572567, 22.04294115, 26.62987909, 15.1444009 ])

In [ ]:
x = x.astype(int)
x

array([28, 22, 22, 26, 23, 32, 26, 23,  8, 32, 22, 38, 16,  3, 21, 22, 21,
       22, 26, 15])

In [ ]:
y = np.random.rand(20) # size =20
y

array([0.07974688, 0.23003977, 0.48976988, 0.6085718 , 0.78603756,
       0.99280096, 0.70561627, 0.94663584, 0.8115525 , 0.79435033,
       0.47321402, 0.59437965, 0.93050705, 0.10600312, 0.24803248,
       0.9113504 , 0.45883182, 0.81320122, 0.39699663, 0.0953968 ])

In [ ]:
pd.DataFrame(data = x, columns = ["Ages"])

Ages
0     28
1     22
2     22
3     26
4     23
5     32
6     26
7     23
8      8
9     32
10    22
11    38
12    16
13     3
14    21
15    22
16    21
17    22
18    26
19    15

In [ ]:
df = pd.DataFrame(data=x,columns=["Ages"])
df.head()

Ages
0    28
1    22
2    22
3    26
4    23

In [ ]:
df["Succession_Rate"] = y

In [ ]:
df.head()

Ages  Succession_Rate
0    28         0.079747
1    22         0.230040
2    22         0.489770
3    26         0.608572
4    23         0.786038

In [ ]:
z = np.random.randint(low = 20, high = 30, size = 20)*1000
z

array([23000, 28000, 28000, 28000, 26000, 26000, 22000, 26000, 22000,
       23000, 26000, 29000, 23000, 27000, 20000, 22000, 20000, 24000,
       29000, 21000])

In [ ]:
df["Customer Salary"] = z

In [ ]:
df.head()

Ages  Succession_Rate  Customer Salary
0    28         0.079747            23000
1    22         0.230040            28000
2    22         0.489770            28000
3    26         0.608572            28000
4    23         0.786038            26000

In [ ]:
df["Customer Salary"].head()

0    23000
1    28000
2    28000
3    28000
4    26000
Name: Customer Salary, dtype: int64

In [ ]:
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df2 = pd.DataFrame(data=m,columns=["1st_Col","2nd_Col","3rd_Col"])
df2

1st_Col  2nd_Col  3rd_Col
0        1        2        3
1        4        5        6
2        7        8        9

In [ ]:
df2.columns = ["Degisken_1","Degisken_2","Degisken_3"]
df2

Degisken_1  Degisken_2  Degisken_3
0           1           2           3
1           4           5           6
2           7           8           9

In [ ]:
type(df2)

pandas.core.frame.DataFrame

In [ ]:
df2.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['Degisken_1', 'Degisken_2', 'Degisken_3'], dtype='object')]

In [ ]:
df2.shape

(3, 3)

In [ ]:
df2.ndim

2

In [ ]:
df2.size

9

In [ ]:
df2.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(df2.values)

numpy.ndarray

## Pandas Elements Operations

In [ ]:
sozluk = {"Ages": [12,45,3,41,16,18,28,34,35,26],
          "SleepPCT":[99,88,77,66,55,44,33,22,11]}

In [ ]:
print(len(sozluk["Ages"]))
print(len(sozluk["SleepPCT"]))

10
9


In [ ]:
pd.DataFrame(data=sozluk,columns=["Ages","SleepPCT"])

ValueError: ignored

In [ ]:
sozluk = {"Ages": [12,45,3,41,16,18,28,34,35,26],
          "SleepPCT":[99,88,77,66,55,44,33,22,11,np.NAN]}
df = pd.DataFrame(data=sozluk,columns=["Ages","SleepPCT"])   
df

Ages  SleepPCT
0    12      99.0
1    45      88.0
2     3      77.0
3    41      66.0
4    16      55.0
5    18      44.0
6    28      33.0
7    34      22.0
8    35      11.0
9    26       NaN

In [ ]:
df[1:3]

Ages  SleepPCT
1    45      88.0
2     3      77.0

In [ ]:
df[1,2]

KeyError: ignored

In [ ]:
df.index = ["a","s","d","f","g","h","j","k","l","i"]
df

Ages  SleepPCT
a    12      99.0
s    45      88.0
d     3      77.0
f    41      66.0
g    16      55.0
h    18      44.0
j    28      33.0
k    34      22.0
l    35      11.0
i    26       NaN

In [ ]:
df.drop("d", axis =0)


Ages  SleepPCT
a    12      99.0
s    45      88.0
f    41      66.0
g    16      55.0
h    18      44.0
j    28      33.0
k    34      22.0
l    35      11.0
i    26       NaN

In [ ]:
df # just like in R. We selected array that nor contains d. If we delete, we need to save. Or you can use intrue argument.

Ages  SleepPCT
a    12      99.0
s    45      88.0
d     3      77.0
f    41      66.0
g    16      55.0
h    18      44.0
j    28      33.0
k    34      22.0
l    35      11.0
i    26       NaN

In [ ]:
#df = df.drop("a",axis =0) 
df.head()

Ages  SleepPCT
s    45      88.0
d     3      77.0
f    41      66.0
g    16      55.0
h    18      44.0

In [ ]:
df.drop("SleepPCT",axis = 1).head(2)

Ages
s    45
d     3

In [ ]:
df.head(2)

Ages  SleepPCT
s    45      88.0
d     3      77.0

In [ ]:
#df = df.drop("SleepPCT",axis=1)
#df.drop("SleepPCT",axis=1,inplace=True)

In [ ]:
# multiple deleting
df.drop(["s","d"],axis=0) # we didn't save.

Ages  SleepPCT
f    41      66.0
g    16      55.0
h    18      44.0
j    28      33.0
k    34      22.0
l    35      11.0
i    26       NaN

In [ ]:
l = ["s","d"]
df.drop(l,axis=0)

Ages  SleepPCT
f    41      66.0
g    16      55.0
h    18      44.0
j    28      33.0
k    34      22.0
l    35      11.0
i    26       NaN

In [ ]:
# questinin "Ages" column in df
"Ages" in df

True

In [ ]:
l = ["Ages","SleepPCT"]
l in df

TypeError: ignored

In [ ]:
for i in l:
  print(i in df)

True
True


In [ ]:
df.head()

Ages  SleepPCT
s    45      88.0
d     3      77.0
f    41      66.0
g    16      55.0
h    18      44.0

In [ ]:
df["AgeSleepRate"] = df["Ages"] * (df["SleepPCT"]/100)
df.head()

Ages  SleepPCT  AgeSleepRate
s    45      88.0         39.60
d     3      77.0          2.31
f    41      66.0         27.06
g    16      55.0          8.80
h    18      44.0          7.92

## Selecting Observation and Feature/Variable (loc, iloc)

In [ ]:
a = np.random.choice(["Data","IT","Accounting","Marketing","HR","Sales Strategy","Bussines Solution","Legal","C_O"],size = 500,p=[0.05,0.2,0.2,0.2,0.1,0.1,0.05,0.05,0.05]) 
print(len(a[a=="Data"]))
print(len(a[a=="IT"]))
print(len(a[a=="Accounting"]))
print(len(a[a=="Marketing"]))
print(len(a[a=="HR"]))
print(len(a[a=="Sales Strategy"]))
print(len(a[a=="Bussines Solution"]))
print(len(a[a=="Legal"]))
print(len(a[a=="C_O"]))

17
102
94
107
54
51
22
25
28


In [ ]:
size = 10_000
df = pd.DataFrame()

df["Ages"] = np.random.randint(30,45,size)
df["Department"] = np.random.choice(["Data","IT","Accounting","Marketing","HR","Sales Strategy","Bussines Solution","Legal","C_O"],size = size,p=[0.05,0.2,0.2,0.2,0.1,0.1,0.05,0.05,0.05]) 
df["Salary"] = np.random.randint(30,60,size)*1000
df["Health Insurance"] = np.random.choice([0,1],size=size,p=[0.2,0.8])
df["Sides"] = np.random.choice([0,1],size=size, p = [0.9,0.1])
df["Efficient"] = np.random.rand(size)
df["Working Hours"] = np.random.normal(8,2,size=size)

In [ ]:
df.head()

Ages         Department  Salary  Health Insurance  Sides  Efficient  \
0    39          Marketing   50000                 1      0   0.566151   
1    30  Bussines Solution   41000                 1      0   0.566872   
2    34          Marketing   44000                 0      0   0.168436   
3    38                C_O   37000                 1      0   0.572405   
4    43         Accounting   30000                 0      0   0.189544   

   Working Hours  
0      10.797529  
1       6.976576  
2       7.971809  
3       8.194448  
4       9.291556

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Ages              10000 non-null  int64  
 1   Department        10000 non-null  object 
 2   Salary            10000 non-null  int64  
 3   Health Insurance  10000 non-null  int64  
 4   Sides             10000 non-null  int64  
 5   Efficient         10000 non-null  float64
 6   Working Hours     10000 non-null  float64
dtypes: float64(2), int64(4), object(1)
memory usage: 547.0+ KB


In [ ]:
df.describe().T

count          mean          std           min  \
Ages              10000.0     36.961700     4.324570     30.000000   
Salary            10000.0  44377.300000  8640.833936  30000.000000   
Health Insurance  10000.0      0.800000     0.400020      0.000000   
Sides             10000.0      0.095000     0.293230      0.000000   
Efficient         10000.0      0.498704     0.289123      0.000092   
Working Hours     10000.0      7.982268     1.976376      0.061215   

                           25%           50%           75%           max  
Ages                 33.000000     37.000000     41.000000     44.000000  
Salary            37000.000000  44000.000000  52000.000000  59000.000000  
Health Insurance      1.000000      1.000000      1.000000      1.000000  
Sides                 0.000000      0.000000      0.000000      1.000000  
Efficient             0.249487      0.495938      0.751196      0.999860  
Working Hours         6.639198      8.003389      9.324201     14.645775

In [ ]:
?df.loc

In [ ]:
df.loc[0] # first observation

Ages                       39
Department          Marketing
Salary                  50000
Health Insurance            1
Sides                       0
Efficient            0.566151
Working Hours       10.797529
Name: 0, dtype: object

In [ ]:
# multiple selecting one by one but more than one obsevation. (fancy)
df.loc[[0,1]]

Ages         Department  Salary  Health Insurance  Sides  Efficient  \
0    39          Marketing   50000                 1      0   0.566151   
1    30  Bussines Solution   41000                 1      0   0.566872   

   Working Hours  
0      10.797529  
1       6.976576

In [ ]:
# multiple selecting with arange
df.loc[0:20]

Ages         Department  Salary  Health Insurance  Sides  Efficient  \
0     39          Marketing   50000                 1      0   0.566151   
1     30  Bussines Solution   41000                 1      0   0.566872   
2     34          Marketing   44000                 0      0   0.168436   
3     38                C_O   37000                 1      0   0.572405   
4     43         Accounting   30000                 0      0   0.189544   
5     33          Marketing   30000                 1      1   0.017228   
6     43     Sales Strategy   56000                 1      0   0.822870   
7     34     Sales Strategy   32000                 1      0   0.052875   
8     33     Sales Strategy   45000                 1      0   0.916966   
9     39          Marketing   35000                 0      0   0.664555   
10    38         Accounting   50000                 1      0   0.866235   
11    38                 IT   49000                 1      0   0.574504   
12    35         Accounting   43000                 0      1   0.205781   
13    32              Legal   48000                 0      0   0.752464   
14    38  Bussines Solution   30000                 1      0   0.145358   
15    36                 IT   40000                 0      0   0.871574   
16    34                C_O   38000                 1      0   0.976962   
17    41          Marketing   31000                 0      1   0.724815   
18    37                 IT   33000                 1      1   0.229530   
19    33                 HR   52000                 1      0   0.057263   
20    34                C_O   35000                 1      0   0.646259   

    Working Hours  
0       10.797529  
1        6.976576  
2        7.971809  
3        8.194448  
4        9.291556  
5       11.165166  
6        9.083137  
7        8.901098  
8        8.101026  
9        9.607905  
10       7.575573  
11       7.611784  
12       8.532774  
13       9.114044  
14      10.590603  
15       8.500617  
16       7.732458  
17       6.232131  
18      10.588974  
19       7.315321  
20      11.343351

In [ ]:
df.loc[0:10,"Department"]

0             Marketing
1     Bussines Solution
2             Marketing
3                   C_O
4            Accounting
5             Marketing
6        Sales Strategy
7        Sales Strategy
8        Sales Strategy
9             Marketing
10           Accounting
Name: Department, dtype: object

In [ ]:
df.loc[0:10,["Department","Salary"]]

Department  Salary
0           Marketing   50000
1   Bussines Solution   41000
2           Marketing   44000
3                 C_O   37000
4          Accounting   30000
5           Marketing   30000
6      Sales Strategy   56000
7      Sales Strategy   32000
8      Sales Strategy   45000
9           Marketing   35000
10         Accounting   50000

In [ ]:
# loc: 0-3 realy 0-3
# iloc: 0-3 is 0,1,2

In [ ]:
df.iloc[:5,:3]

Ages         Department  Salary
0    39          Marketing   50000
1    30  Bussines Solution   41000
2    34          Marketing   44000
3    38                C_O   37000
4    43         Accounting   30000

In [ ]:
df.loc[:5,:3]

TypeError: ignored

In [ ]:
df.loc[:5,"Ages":"Sides"]


Ages         Department  Salary  Health Insurance  Sides
0    39          Marketing   50000                 1      0
1    30  Bussines Solution   41000                 1      0
2    34          Marketing   44000                 0      0
3    38                C_O   37000                 1      0
4    43         Accounting   30000                 0      0
5    33          Marketing   30000                 1      1

In [ ]:
df.iloc[0:3][:5]

Ages         Department  Salary  Health Insurance  Sides  Efficient  \
0    39          Marketing   50000                 1      0   0.566151   
1    30  Bussines Solution   41000                 1      0   0.566872   
2    34          Marketing   44000                 0      0   0.168436   

   Working Hours  
0      10.797529  
1       6.976576  
2       7.971809

In [ ]:
df.loc[:3]["Ages"]

0    39
1    30
2    34
3    38
Name: Ages, dtype: int64

In [ ]:
df.iloc[0:2]["Ages"]

0    39
1    30
Name: Ages, dtype: int64

## Conditions

In [ ]:
 df.head()

Ages         Department  Salary  Health Insurance  Sides  Efficient  \
0    39          Marketing   50000                 1      0   0.566151   
1    30  Bussines Solution   41000                 1      0   0.566872   
2    34          Marketing   44000                 0      0   0.168436   
3    38                C_O   37000                 1      0   0.572405   
4    43         Accounting   30000                 0      0   0.189544   

   Working Hours  
0      10.797529  
1       6.976576  
2       7.971809  
3       8.194448  
4       9.291556

In [ ]:
df["Ages"]

0       39
1       30
2       34
3       38
4       43
        ..
9995    41
9996    33
9997    43
9998    40
9999    42
Name: Ages, Length: 10000, dtype: int64

In [ ]:
df["Ages"][0:5]

0    39
1    30
2    34
3    38
4    43
Name: Ages, dtype: int64

In [ ]:
df[["Ages","Salary"]][0:5]

Ages  Salary
0    39   50000
1    30   41000
2    34   44000
3    38   37000
4    43   30000

In [ ]:
df[0:5]["Ages"]

0    39
1    30
2    34
3    38
4    43
Name: Ages, dtype: int64

In [ ]:
df[0:5][["Ages","Salary"]]

Ages  Salary
0    39   50000
1    30   41000
2    34   44000
3    38   37000
4    43   30000

In [ ]:
df["Ages"].max()

44

In [ ]:
df["Salary"].mean()

44377.3

In [ ]:
# get employees whose salary greater than 50000
df[df["Salary"]>50000]

Ages      Department  Salary  Health Insurance  Sides  Efficient  \
6       43  Sales Strategy   56000                 1      0   0.822870   
19      33              HR   52000                 1      0   0.057263   
25      36              HR   57000                 1      0   0.770448   
28      39            Data   59000                 1      0   0.518984   
32      37       Marketing   55000                 1      0   0.662990   
...    ...             ...     ...               ...    ...        ...   
9985    42  Sales Strategy   56000                 1      0   0.030682   
9990    31       Marketing   52000                 1      0   0.589219   
9994    38  Sales Strategy   54000                 0      0   0.086927   
9995    41      Accounting   54000                 1      0   0.635484   
9998    40              IT   57000                 1      0   0.815401   

      Working Hours  
6          9.083137  
19         7.315321  
25         7.880422  
28         9.959764  
32         6.058639  
...             ...  
9985       5.488356  
9990       6.431688  
9994       8.806282  
9995       7.881960  
9998       8.419935  

[2947 rows x 7 columns]

In [ ]:
#find number of employees 
len(df[df["Salary"]>50000])

2947

In [ ]:
# find employees whose salary greater than mean salary
df[df["Salary"]>df["Salary"].mean()] # or
df[df.Salary > df.Salary.mean()]

Ages      Department  Salary  Health Insurance  Sides  Efficient  \
0       39       Marketing   50000                 1      0   0.566151   
6       43  Sales Strategy   56000                 1      0   0.822870   
8       33  Sales Strategy   45000                 1      0   0.916966   
10      38      Accounting   50000                 1      0   0.866235   
11      38              IT   49000                 1      0   0.574504   
...    ...             ...     ...               ...    ...        ...   
9993    44  Sales Strategy   45000                 1      1   0.445260   
9994    38  Sales Strategy   54000                 0      0   0.086927   
9995    41      Accounting   54000                 1      0   0.635484   
9997    43      Accounting   48000                 0      0   0.213592   
9998    40              IT   57000                 1      0   0.815401   

      Working Hours  
0         10.797529  
6          9.083137  
8          8.101026  
10         7.575573  
11         7.611784  
...             ...  
9993      12.590152  
9994       8.806282  
9995       7.881960  
9997       6.695385  
9998       8.419935  

[4922 rows x 7 columns]

In [ ]:
# find employees whose salary greater than mean salary BUT just get their ages
df[df.Salary > df.Salary.mean()]["Ages"]
len(df[df.Salary > df.Salary.mean()]["Ages"])

4922

In [ ]:
df[df.Salary > 50_000]["Department"]

6       Sales Strategy
19                  HR
25                  HR
28                Data
32           Marketing
             ...      
9985    Sales Strategy
9990         Marketing
9994    Sales Strategy
9995        Accounting
9998                IT
Name: Department, Length: 2947, dtype: object

In [ ]:
# maaşı 50k'dan fazla olan vericilerin sayısını bul.
findDep = df[df.Salary > 50_000]["Department"]
findDep[findDep=="Data"]
len(findDep[findDep=="Data"])

126

In [ ]:
# maaşı 50 ile 45 arasında olan ve yan hakları olmayan accountingleri bul
getEmp = df[(df.Salary<50_000) & (df.Salary>45_000)]
targetEmp = getEmp[(getEmp.Sides==1) & (getEmp.Department =="Accounting") ]
len(targetEmp)

20

In [ ]:
df.loc[(df.Salary<50_000) & (df.Salary>45_000),["Department","Sides"]]

Department  Sides
11                   IT      0
13                Legal      0
22                 Data      0
46            Marketing      0
64                  C_O      0
...                 ...    ...
9976          Marketing      1
9977                C_O      1
9978  Bussines Solution      0
9982              Legal      0
9997         Accounting      0

[1294 rows x 2 columns]

In [ ]:
getEmp = df.loc[(df.Salary<50_000) & (df.Salary>45_000),["Department","Sides"]]  # sana görme imkanı tanıdığı için daha kulanışlı
type(getEmp)
target = getEmp[(getEmp.Department == "Accounting") & (getEmp.Sides == 1)]
len(target)

20

In [ ]:
getEmp = df[(df.Salary<50_000) & (df.Salary>45_000)][["Department","Sides"]]  # yukarıdakinin alternatifi illa vardır :)
targetEmp = getEmp[(getEmp.Sides==1) & (getEmp.Department =="Accounting") ]
len(targetEmp)


20

## Join DataFrames

In [ ]:
m1 = np.random.randint(low= 5, high=20,size=(3,5))
df1 = pd.DataFrame(m1)
df2 = df1+100

In [ ]:
 pd.concat([df1,df2])

0    1    2    3    4
0   18    7   15    9    9
1   19   14   15    5   17
2    5   16   10   13   15
0  118  107  115  109  109
1  119  114  115  105  117
2  105  116  110  113  115

In [ ]:
?pd.concat

In [ ]:
pd.concat([df1,df2],ignore_index=True)

0    1    2    3    4
0   18    7   15    9    9
1   19   14   15    5   17
2    5   16   10   13   15
3  118  107  115  109  109
4  119  114  115  105  117
5  105  116  110  113  115

In [ ]:
df1.columns = [1,2,3,4,5]

In [ ]:
pd.concat([df1,df2])

0    1    2    3    4     5
0    NaN   18    7   15    9   9.0
1    NaN   19   14   15    5  17.0
2    NaN    5   16   10   13  15.0
0  118.0  107  115  109  109   NaN
1  119.0  114  115  105  117   NaN
2  105.0  116  110  113  115   NaN

In [ ]:
pd.concat([df1,df2],join = "inner")

1    2    3    4
0   18    7   15    9
1   19   14   15    5
2    5   16   10   13
0  107  115  109  109
1  114  115  105  117
2  116  110  113  115

In [ ]:
a= pd.concat([df1,df2], axis = 0)
a.reset_index(drop=True)
a

0    1    2    3    4     5
0    NaN   18    7   15    9   9.0
1    NaN   19   14   15    5  17.0
2    NaN    5   16   10   13  15.0
0  118.0  107  115  109  109   NaN
1  119.0  114  115  105  117   NaN
2  105.0  116  110  113  115   NaN

## Advanced Join

In [ ]:
df1 = pd.DataFrame(data= {"Calisanlar":["Ali","Veli","Ayşe","Fatma"],
                          "grup": ["Muahsebe", "Muhendislik","Muhendislik","IK"]})
df1

Calisanlar         grup
0        Ali     Muahsebe
1       Veli  Muhendislik
2       Ayşe  Muhendislik
3      Fatma           IK

In [ ]:
df2 = pd.DataFrame({"Calisanlar":["Ali","Veli","Ayşe","Fatma"],
                    "ilk_giris":[2010,2009,2014,2019]})
df2

Calisanlar  ilk_giris
0        Ali       2010
1       Veli       2009
2       Ayşe       2014
3      Fatma       2019

In [ ]:
# birebir birleştirme, tüm elemanların iki verisetinde de birebir bulunması

In [ ]:
?pd.merge

In [ ]:
df3 = pd.merge(left=df1,right=df2,left_on = "Calisanlar",right_on="Calisanlar")
df3

Calisanlar         grup  ilk_giris
0        Ali     Muahsebe       2010
1       Veli  Muhendislik       2009
2       Ayşe  Muhendislik       2014
3      Fatma           IK       2019

In [ ]:
# birden çok birleştirme

In [ ]:
df4 = pd.DataFrame({"grup": ["Muahsebe","Muhendislik","IK",],
                    "mudur": ["Caner","Mustafa","Berkcan"]})

In [ ]:
pd.merge(df3,df4)

Calisanlar         grup  ilk_giris    mudur
0        Ali     Muahsebe       2010    Caner
1       Veli  Muhendislik       2009  Mustafa
2       Ayşe  Muhendislik       2014  Mustafa
3      Fatma           IK       2019  Berkcan

In [ ]:
# kolon isimleri aynıyken "on" parametresini set etmene gerek kalmıyor.

In [ ]:
#çoktan çoktan

In [ ]:
df5 = pd.DataFrame({"grup":["Muahsebe","Muahsebe","Muhendislik","Muhendislik","IK","IK"],
                    "yetenekler":["matematik","excel","kodlama","linux","excel","yonetim"]})

In [ ]:
df5

grup yetenekler
0     Muahsebe  matematik
1     Muahsebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           IK      excel
5           IK    yonetim

In [ ]:
pd.merge(df1,df5)

Calisanlar         grup yetenekler
0        Ali     Muahsebe  matematik
1        Ali     Muahsebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayşe  Muhendislik    kodlama
5       Ayşe  Muhendislik      linux
6      Fatma           IK      excel
7      Fatma           IK    yonetim

## Aggregation and Grouping (Toplulaştırma ve Gruplama)

Basit ve bilinmesi faydalı toplulaştırma fonksiyonları:
* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

Daha sonradan bu fonkiyonları Keşifçi veri setinde analiz ederken kullanacağız.


In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset("planets")

In [ ]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [ ]:
df.shape

(1035, 6)

In [ ]:
df.ndim

2

In [ ]:
df.size

6210

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [ ]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [ ]:
print("df.mean() ",df.mean())
print("====================")
print("df['mass'].mean",df.mass.mean())

df.mean()  number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64
df['mass'].mean 2.6381605847953216


<ipython-input-31-e6bacefeda87>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("df.mean() ",df.mean())


In [ ]:
print("df.count()",df.count())


df.count() method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64


In [ ]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [ ]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

##Grouping

In [ ]:
df = pd.DataFrame(data = {"gruplar": ["A","B","C","A","B","C"],
                          "veri": [10,11,52,23,43,55]},
                  columns = ["gruplar","veri"])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [ ]:
df.groupby("gruplar")

In [ ]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [ ]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [ ]:
df.groupby("gruplar").count()

veri
gruplar      
A           2
B           2
C           2

In [ ]:
df = sns.load_dataset("planets")

In [ ]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [ ]:
df.groupby("method")["method"].count()

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           38
Microlensing                      23
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          4
Name: method, dtype: int64

In [ ]:
df.groupby("method").sum() # method sınıflarının, sayısal featurlardaki toplamlarını verior!! Maaş toplamı ya da seçim sonucu türünde işe yarar.

number  orbital_period        mass   distance  \
method                                                                         
Astrometry                          2    1.262360e+03     0.00000      35.75   
Eclipse Timing Variations          15    4.276480e+04    10.25000    1261.44   
Imaging                            50    1.418973e+06     0.00000    2166.91   
Microlensing                       27    2.207500e+04     0.00000   41440.00   
Orbital Brightness Modulation       5    2.127920e+00     0.00000    2360.00   
Pulsar Timing                      11    3.671511e+04     0.00000    1200.00   
Pulsation Timing Variations         1    1.170000e+03     0.00000       0.00   
Radial Velocity                   952    4.553151e+05  1341.65638   27348.11   
Transit                           776    8.377523e+03     1.47000  134242.77   
Transit Timing Variations           9    2.393505e+02     0.00000    3313.00   

                                  year  
method                                  
Astrometry                        4023  
Eclipse Timing Variations        18090  
Imaging                          76347  
Microlensing                     46225  
Orbital Brightness Modulation     6035  
Pulsar Timing                     9992  
Pulsation Timing Variations       2007  
Radial Velocity                1110158  
Transit                         798461  
Transit Timing Variations         8050

In [ ]:
df.groupby("number")["number"].count() # adet bilgisi veriyor!!!

number
1    595
2    259
3     88
4     32
5     30
6     24
7      7
Name: number, dtype: int64

Groupby fonksiyonu genelde tek başına bir işe yaramaz. Aggregation fonksiyonları ile beraber kullanıldıklarında bir sonuç/ değer üretirler.

In [ ]:
# Methodların sınıflarına göre gezegenlerin uzaklığının ortalamsını alalımm
df.groupby("method")["distance"].mean()

method
Astrometry                         17.875000
Eclipse Timing Variations         315.360000
Imaging                            67.715937
Microlensing                     4144.000000
Orbital Brightness Modulation    1180.000000
Pulsar Timing                    1200.000000
Pulsation Timing Variations              NaN
Radial Velocity                    51.600208
Transit                           599.298080
Transit Timing Variations        1104.333333
Name: distance, dtype: float64

In [ ]:
type(df.groupby("method")["distance"].mean())

pandas.core.series.Series

In [ ]:
x = df.groupby("method")["distance"].mean()
len(x)

10

In [ ]:
df.groupby("method")["distance"].describe()

count         mean          std      min  \
method                                                                    
Astrometry                       2.0    17.875000     4.094148    14.98   
Eclipse Timing Variations        4.0   315.360000   213.203907   130.72   
Imaging                         32.0    67.715937    53.736817     7.69   
Microlensing                    10.0  4144.000000  2076.611556  1760.00   
Orbital Brightness Modulation    2.0  1180.000000     0.000000  1180.00   
Pulsar Timing                    1.0  1200.000000          NaN  1200.00   
Pulsation Timing Variations      0.0          NaN          NaN      NaN   
Radial Velocity                530.0    51.600208    45.559381     1.35   
Transit                        224.0   599.298080   913.876990    38.00   
Transit Timing Variations        3.0  1104.333333   915.819487   339.00   

                                     25%       50%        75%      max  
method                                                                  
Astrometry                       16.4275    17.875    19.3225    20.77  
Eclipse Timing Variations       130.7200   315.360   500.0000   500.00  
Imaging                          22.1450    40.395   132.6975   165.00  
Microlensing                   2627.5000  3840.000  4747.5000  7720.00  
Orbital Brightness Modulation  1180.0000  1180.000  1180.0000  1180.00  
Pulsar Timing                  1200.0000  1200.000  1200.0000  1200.00  
Pulsation Timing Variations          NaN       NaN        NaN      NaN  
Radial Velocity                  24.4125    40.445    59.2175   354.00  
Transit                         200.0000   341.000   650.0000  8500.00  
Transit Timing Variations       597.0000   855.000  1487.0000  2119.00

## Aggregate, Filter, Transform, Apply

In [ ]:
df = pd.DataFrame(data = {"gruplar": ["A","B","C","A","B","C"],
                          "degisken1": [10,11,52,23,43,55],
                          "degisken2": [20,30,40,50,60,70]},
                  columns = ["gruplar","degisken1","degisken2"])
df

gruplar  degisken1  degisken2
0       A         10         20
1       B         11         30
2       C         52         40
3       A         23         50
4       B         43         60
5       C         55         70

In [ ]:
# agg, birden fazla toplaştırma fonksiyonunu bir arada kullanmak için idealdir.

In [ ]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.5       35.0
B             27.0       45.0
C             53.5       55.0

In [ ]:
df.groupby("gruplar").min()

degisken1  degisken2
gruplar                      
A               10         20
B               11         30
C               52         40

In [ ]:
df.groupby("gruplar").aggregate(["min", np.median, max])

degisken1            degisken2           
              min median max       min median max
gruplar                                          
A              10   16.5  23        20   35.0  50
B              11   27.0  43        30   45.0  60
C              52   53.5  55        40   55.0  70

pandasın içinde olan fonksiyonları tırnaklı veya tırnaksız yazabiliriz. Ama olmayanları (np.median gibi) tırnaksız belirtmemiz gerekiyor. Clean code babında, pandas içerisindekileri tırnaklı diğerlerini tırnaksız yazmak daha okunabilir kılar.

In [ ]:
# şimdide değişkenler için aynı değilde farklı aggregate fonskiyonları kullanalım
df.groupby("gruplar").aggregate({"degisken1":"min","degisken2":"max"})

degisken1  degisken2
gruplar                      
A               10         50
B               11         60
C               52         70

In [ ]:
## filter function, kendin sorgu fonksiyonunu tasarlaman için kullanacaksın. Daha karmaşık sorguları, kendin fonksiyon tanımayıp ver, set,n, f,ltrelemek için kullanabilirsin.

In [ ]:
df = pd.DataFrame(data = {"gruplar": ["A","B","C","A","B","C"],
                          "degisken1": [10,11,52,23,43,55],
                          "degisken2": [20,30,40,50,60,70]},
                  columns = ["gruplar","degisken1","degisken2"])
df

gruplar  degisken1  degisken2
0       A         10         20
1       B         11         30
2       C         52         40
3       A         23         50
4       B         43         60
5       C         55         70

In [ ]:
def filter_func(x):
  return x["degisken1"].std()>9

In [ ]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
0       A         10         20
1       B         11         30
3       A         23         50
4       B         43         60

In [ ]:
df.groupby("gruplar").std()

degisken1  degisken2
gruplar                      
A         9.192388  21.213203
B        22.627417  21.213203
C         2.121320  21.213203

In [ ]:
## transform func(), veri setinde kendin bir değişiklik yapmak istediğind ekullanacağın fonksiyondur. Pandasın içerisinde olmayan dönüşümleri yine kendi tanımayacağın fonk
# ile transforma verir ve hedefe uaşırsın.

In [ ]:
df = pd.DataFrame(data = {"gruplar": ["A","B","C","A","B","C"],
                          "degisken1": [10,11,52,23,43,55],
                          "degisken2": [20,30,40,50,60,70]},
                  columns = ["gruplar","degisken1","degisken2"])
df

gruplar  degisken1  degisken2
0       A         10         20
1       B         11         30
2       C         52         40
3       A         23         50
4       B         43         60
5       C         55         70

In [ ]:
df_a = df.iloc[:,1:3]

In [ ]:
df_a.transform(lambda x: x-x.mean())

degisken1  degisken2
0 -22.333333      -25.0
1 -21.333333      -15.0
2  19.666667       -5.0
3  -9.333333        5.0
4  10.666667       15.0
5  22.666667       25.0

In [ ]:
df_a

degisken1  degisken2
0         10         20
1         11         30
2         52         40
3         23         50
4         43         60
5         55         70

In [ ]:
# standart normal dönüşümü uygulayalım
df_a.transform(lambda x: (x-x.mean())/x.std())

degisken1  degisken2
0  -1.101533  -1.336306
1  -1.052210  -0.801784
2   0.970006  -0.267261
3  -0.460342   0.267261
4   0.526105   0.801784
5   1.117974   1.336306

In [ ]:
## apply func(), tıpkı filter ve transform gibi değişkenler (bu sefer veriler değil) üzerinde gezinme yeteneği olan,
## toplulaştırma amacıyla kullanılan bi fonkksiyondur.

In [ ]:
df

gruplar  degisken1  degisken2
0       A         10         20
1       B         11         30
2       C         52         40
3       A         23         50
4       B         43         60
5       C         55         70

In [ ]:
df_a = df.iloc[:,1:]

In [ ]:
df_a.apply(np.sum)

degisken1    194
degisken2    270
dtype: int64

In [ ]:
df_a.apply(np.mean)

degisken1    32.333333
degisken2    45.000000
dtype: float64

In [ ]:
df.groupby("gruplar").apply(np.mean)

/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:3472: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:3472: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


degisken1  degisken2
gruplar                      
A             16.5       35.0
B             27.0       45.0
C             53.5       55.0

##Pivot Tablolar

In [ ]:
?sns.load_dataset

In [ ]:
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
titanic.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [ ]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [ ]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
titanic.groupby(["sex","class"])[["survived"]].mean()

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [ ]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean") # elin bbuna alışırsa daha iyi olur

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [ ]:
# pivot table ile:
titanic.pivot_table("survived",index="sex",columns="class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
age = pd.cut(titanic["age"], [0,18,90])
age.head()

0    (18, 90]
1    (18, 90]
2    (18, 90]
3    (18, 90]
4    (18, 90]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [ ]:
titanic.pivot_table("survived",["sex",age],"class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663