# Numpy Methods

### 1. arange

In [2]:
import numpy as np

In [4]:
myNumpyList = np.arange(0,10)
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [7]:
myNumpyList = np.arange(0,10,2) ##two-steps
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[0 2 4 6 8]


### 2.zeros

it just makes an array that consist of zeros.

In [11]:
myNumpyList = np.zeros(5)  ##Parameter = how many zeros do u want
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[0. 0. 0. 0. 0.]


In [12]:
myNumpyList = np.zeros((2,2))  ## a two by two matrix
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[[0. 0.]
 [0. 0.]]


### 3.ones

it just makes an array that consist of ones.

In [13]:
myNumpyList = np.ones(5)
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]


In [14]:
myNumpyList = np.ones((5,5))
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 3.linspace

each space has an equal distance. <br/>
Note: mostly you will Use this func at Data Science.

In [4]:
myNumpyList = np.linspace(0,20,5)  ##make an five-element array between of 0 and 20
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[ 0.  5. 10. 15. 20.]


In [19]:
myNumpyList = np.linspace(0,20,10)  ##make an ten-element array between of 0 and 20
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [20]:
myNumpyList = np.linspace(0,20,11)  ##make an eleven-element array between of 0 and 20
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [28]:
myNumpyList = np.linspace(1,20,20)  ##make an twenty-element array between of 0 and 20
print(type(myNumpyList))
print(myNumpyList)

<class 'numpy.ndarray'>
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


### 4.eye

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 5.random

#### 4.1 random.rand()

it generates numpy array that consist of random numbers.

In [33]:
np.random.rand(8)

array([0.55962076, 0.98717845, 0.2327944 , 0.6111573 , 0.32128128,
       0.83543985, 0.93849841, 0.56018017])

In [34]:
np.random.rand(4,4)

array([[0.66944154, 0.24615179, 0.52646502, 0.93938031],
       [0.75914836, 0.57196691, 0.71961451, 0.64320695],
       [0.23139699, 0.19217937, 0.09402497, 0.0193277 ],
       [0.48044548, 0.29781336, 0.32568222, 0.6120245 ]])

### 4.2 np.random.randint()

it generates random number. As you know from randomlibrary.

In [38]:
np.random.randint(1,10)  ##Generates between the specified values. ten not include

1

In [40]:
np.random.randint(1,10,2) #it generates a random list that has two elements

array([5, 8])