# Matrix Indexes

In [1]:
import numpy as np

In [2]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]
myNumpyMatrix = np.array(myMatrix)

In [3]:
myNumpyMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
myNumpyMatrix[0]  ##row

array([1, 2, 3])

In [5]:
myNumpyMatrix[0][1]  ##row,coll

2

Note: myNumpyMatrix[0][1] == myNumpyMatrix[0,1]

In [8]:
myNumpyMatrix[1:,2]   

array([6, 9])

In [7]:
myNumpyMatrix[1,1:]

array([5, 6])

In [10]:
myNumpyMatrix[1,:2]         #not include finish index

array([4, 5])

In [11]:
myMatrix2 = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]
MyNumpyMatrix2 = np.array(myMatrix2)

In [13]:
MyNumpyMatrix2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
MyNumpyMatrix2[[0,2,4]]    ##0.2.4. rows, 

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])